### ISSUE TITLE
Tracker for to-rebase openSUSE patches

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#292]
This is not mostly for downstream openSUSE as we have list of patches we will have to review prior the release, maybe even some can be upstreamed, but it is mostly for downstream review we have to do.

List of stuff to check:
 - [x] devel-provide-is-devel-package.diff
 - [x] docdata-examples.diff
 - [x] check-for-self-provides.diff
 - [x] invalid-filerequires.diff
 - [x] no-doc-for-lib.diff
 - [x] only-reg-files-are-scripts.diff
 - [x] rpmgroup-checks.diff
 - [x] rpmlint-slpp-NUM-NUM.patch
 - [x] suse-binarieschecks.diff
 - [x] suse-pkg-config-check.diff
 - [x] suse-python3-naming-policy.diff
 - [x] suse-rpmlint-all-pie.patch
 - [x] suse-shlib-devel-dependency.diff
 - [x] suse-skip-macro-expansion.diff
 - [x] suse-spdx-license-exceptions.patch
 - [x] suse-version.diff

**Comment by scarabeusiv** [comment]
@mimi1vx @kstreitova @marxin ^^ :)

**Comment by marxin** [comment]
@scarabeusiv Thanks for it. Can you please also upload the patches to https://gist.github.com/ ?
What's bad about the issue is that I can't modify your commend with the checklist :/

**Comment by scarabeusiv** [comment]
@marxin kein ahnung. Just tell me on irc what I should check :)) The gist will take me a bit as I am still doing the training so it might take me a bit :)

**Comment by marxin** [comment]
Ok, there's a gist for all the patches: https://gist.github.com/marxin/4345da142ebf76117b6acd08d015c37e

**Comment by marxin** [comment]
> @marxin kein ahnung. Just tell me on irc what I should check :)) The gist will take me a bit as I am still doing the training so it might take me a bit :)

Ok, please check `suse-binarieschecks.diff`, all stuff in the patch has been ported. And please sort the list of the patches ;)

**Comment by scarabeusiv** [comment]
But the list is sorted alphabetically. :)

**Comment by marxin** [comment]
About `only-reg-files-are-scripts.diff`: Can we drop `./rpmlint/checks/InitScriptCheck.py` as `init.d` is dead?

**Comment by scarabeusiv** [comment]
I think @Conan-Kudo said some distro still uses them, but I wonder if we really have such a product somewhere that is rpm based yet non-systemd.

**Comment by Conan-Kudo** [comment]
ALT Linux has a non-systemd variant, and PCLinuxOS still uses the RH/MDV sysvinit style environment, too.

**Comment by Conan-Kudo** [comment]
@scarabeusiv @marxin Please note that it is not acceptable to submit pull requests with meaningless commits like the one in #303. 

If you intend to rework those for upstreaming, please take the modicum of care to actually do proper descriptions of the patches, what they do, and why they're useful.

**Comment by marxin** [comment]
> ALT Linux has a non-systemd variant, and PCLinuxOS still uses the RH/MDV sysvinit style environment, too.

I see, thanks.
@scarabeusiv: please mark `only-reg-files-are-scripts.diff` as checked as we don't want to port it to rpmlint as we're not interested in a `init.d` check.

**Comment by marxin** [comment]
@scarabeusiv about `invalid-filerequires.diff`: can't see any warning reported with `invalid-filerequires.diff` patch. Do we still want to port it?

**Comment by marxin** [comment]
@scarabeusiv can't see any warning from `suse-pkg-config-check.diff`, do we really want to port it?

**Comment by marxin** [comment]
@scarabeusiv: `suse-python3-naming-policy.diff` - can you please make an opinion about this one?

**Comment by marxin** [comment]
@scarabeusiv Assign the issue to me please.

**Comment by scarabeusiv** [comment]
> @scarabeusiv can't see any warning from `suse-pkg-config-check.diff`, do we really want to port it?

if there are no catches I don't see tests in rpmlint-tests so that one probably can die, if it was fatal someone can resurrect it later on.

**Comment by scarabeusiv** [comment]
> @scarabeusiv: `suse-python3-naming-policy.diff` - can you please make an opinion about this one?

Yea this one is weird, but the whole naming policy module is weird and should be re-invented. I think we will need to sit down and figure the pkg naming scheme after py2 is dead.

**Comment by scarabeusiv** [comment]
suse-rpmlint-all-pie.patch - we need to check up if it really makes sense to make some of the errors to warnings or not.

**Comment by marxin** [comment]
@scarabeusiv: Please check `devel-provide-is-devel-package.diff`.
About `rpmlint-slpp-NUM-NUM.patch`: looking at the history, I can't see a revision where we would have `[\d_]` group in the regex?

**Comment by scarabeusiv** [comment]
@marxin I suppose the [\d_] is another patch that we ship in openSUSE only :( but it was here as a pr from ludwig and it just needed a rebase...

**Comment by marxin** [comment]
> @marxin I suppose the [\d_] is another patch that we ship in openSUSE only :( but it was here as a pr from ludwig and it just needed a rebase...

Can you please send me a link for it?

**Comment by scarabeusiv** [comment]
@marxin https://github.com/rpm-software-management/rpmlint/pull/59

**Comment by marxin** [comment]
> @marxin I suppose the [\d_] is another patch that we ship in openSUSE only :( but it was here as a pr from ludwig and it just needed a rebase...

Ok, now I can see it. I'll bundle all these patches into a one PR to `opensuse` branch.

**Comment by marxin** [comment]
@scarabeusiv : Btw. do we want to upstream `suse-skip-macro-expansion-diff` as it can cause trouble to other distros as well?

**Comment by marxin** [comment]
@scarabeusiv : Please check `suse-rpmlint-all-pie.patch`.

**Comment by scarabeusiv** [comment]
@marxin re `suse-skip-macro-expansion-diff` we should make that one upstream i guess, the test is not worth the hassle it causes on most distros, and we can reintroduce it always in a better way later.

Also re #59 that one imo could be really upstream, maybe even the other one with option for SLPP policy as a config option as other distros have same policy like we do.

**Comment by marxin** [comment]
> Also re #59 that one imo could be really upstream, maybe even the other one with option for SLPP policy as a config option as other distros have same policy like we do.

Ok, which option name and possible option values do you suggest?

**Comment by scarabeusiv** [comment]
I dunno slpp_compilant as boolean? We can put a link to debian slpp explanation...

**Comment by marxin** [comment]
@scarabeusiv Please check `suse-skip-macro-expansion.diff` as done.

**Comment by marxin** [comment]
@scarabeusiv And please check `suse-shlib-devel-dependency.diff`.

**Comment by marxin** [comment]
@scarabeus : Please check the last checkbox and close.
